language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
branches:
  only:
    - master
    - dev
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/dotnet-publish.sh
  - ./scripts/docker-publish-travis.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always


