version: "2"
services:
  memotime-backend:
    image: bielu000/memotime.backend:latest
    links:
      - mongo
    ports:
      - '5000:5050'
  
  memotime-ui:
    image: bielu000/memotime.ui:latest
    links:
      - memotime.backend
    ports: 
      - '8888:80'

  mongo:
    image: mongo
    volumes:
      - /home:/data/db
    ports:
      - '27017:27017'
