version: "2"
services:
  memotime-backend:
    image: bielu000/memotime.backend:latest
    links:
      - mssql
    ports:
      - '5000:5050'
  
  memotime-ui:
    image: bielu000/memotime.ui:latest
    links:
      - memotime-backend
    ports: 
      - '8888:80'

  mssql:
    image: microsoft/mssql-server-linux:latest
    volumes:
      - /home:/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zaq1asdfgh
    ports:
      - "1433:1433"

